# Generated by Django 5.0.6 on 2024-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_username_ticket_delete_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
