# Generated by Django 5.0.6 on 2024-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_ticket_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="recipient_email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
