# Generated by Django 5.0.6 on 2024-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_ticket_recipient_email_alter_ticket_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="user_email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
