# Generated by Django 5.0.6 on 2024-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_ticket_user_email_alter_user_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Customer",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="user",
            new_name="customer",
        ),
    ]
