# Generated by Django 5.0.6 on 2024-07-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_user_customer_rename_user_ticket_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
