# Generated by Django 5.0.6 on 2024-07-09 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_ticket_customer_delete_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="recipient_email",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="user_email",
        ),
    ]
