# Generated by Django 5.0.6 on 2024-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0009_remove_ticket_recipient_email_remove_ticket_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="recipient_email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user_email",
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
