# Generated by Django 5.0.6 on 2024-07-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="company",
        ),
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="accounts.sector",
            ),
        ),
    ]
