# Generated by Django 5.0.6 on 2024-07-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_sector_company_company_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="company",
                to="accounts.sector",
            ),
        ),
    ]
